server:
  http_listen_port: 8000
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: https:/loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-logs
    static_configs:
    - targets:
        - localhost
      labels:
        job: docker-logs
        __path__: /var/lib/docker/containers/*/*.log

    pipeline_stages:

    - json:
        expressions:
          stream: stream
          attrs: attrs
          tag: attrs.tag
    - regex:
        expression