global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: docker

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerting.yml

scrape_configs:
  - job_name: fastapi
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: node
    static_configs:
      - targets: ["host.docker.internal:9100"]
    relabel_configs:
      - source_labels: [__address__]
        regex: 'host\.docker\.internal:9100'
        target_label: instance
        replacement: docker-host

  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]